import Head from "next/head";
import Home from "@/components/pages/home.page";
// import WatsonWrapper,{startRecord} from "@/components/watsonWrapper";
// import $ from "jquery";
export default function Page() {
  // setInterval(() => {
  //   console.log("home")
  //   var watsonChatHome = $(".WatsonAssistantChatHost");
  //   var recordStartBtn = $("button#start_record.WACInputContainer__SendButton.WAC__button--base.WAC__button--primary.record");
  //   var recordingBtn = $("button#recording.WACInputContainer__SendButton.WAC__button--base.WAC__button--primary.record");
  //   console.log($(".WACInputContainer"))
  //   if(watsonChatHome.length != 0 && recordStartBtn.length == 0 && recordingBtn.length == 0){
  //     $(".WACInputContainer").append('<button class="WACInputContainer__SendButton WAC__button--base WAC__button--primary record" style="background-color: white;border: solid 1px cadetblue;" id="start_record" type="button" aria-label="Click to record your voice"><img style="width:24px; height:24px" src="https://www.vhv.rs/dpng/d/144-1448006_microphone-icon-logo-design-mic-symbol-music-mic.png"/></button>');
  //     $(".WACInputContainer").append('<button class="WACInputContainer__SendButton WAC__button--base WAC__button--primary record" style="display:none; background-color: white;border: solid 1px cadetblue;" id="recording" type="button" aria-label="Click to record your voice"><img style="width:40px; height:40px" src="https://assets-v2.lottiefiles.com/a/3073009a-1175-11ee-911a-2f7877ab6fd3/3DMmrkykp0.gif"/></button>');    
  //   }
  //   $('.record').on('mousedown', function() {
  //     // Action to perform when the button is pressed
  //     $("button#start_record.WACInputContainer__SendButton.WAC__button--base.WAC__button--primary.record").hide();
  //     $("button#recording.WACInputContainer__SendButton.WAC__button--base.WAC__button--primary.record").show();
  //     startRecord()
  //   });

  //   $('.record').on('mouseup', async function() {
  //     $("button#start_record.WACInputContainer__SendButton.WAC__button--base.WAC__button--primary.record").show();
  //     $("button#recording.WACInputContainer__SendButton.WAC__button--base.WAC__button--primary.record").hide();     
  //   });       
  // }, 1000);  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
}